services:
  nota-ri-db:
    image: busca-postgres:0.0.11
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    container_name: nota-ri-db
    networks:
      - busca-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nota_ri
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - nota_ri_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nota_ri"]
      interval: 5s
      retries: 5
      timeout: 3s

  material-db:
    image: busca-postgres:0.0.11
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    container_name: material-db
    networks:
      - busca-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: material
    expose:
      - "5432"
    ports:
      - "5430:5432"
    volumes:
      - material_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d material"]
      interval: 5s
      retries: 5
      timeout: 3s


volumes:
  nota_ri_postgres_data:
    driver: local
  material_postgres_data:
    driver: local

networks:
  busca-net:
    name: busca-net
    external: true
